# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      # run tests!
      - run: ./gradlew test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/unit-test/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/unit-test/ \;
          when: always
      - store_test_results:
          path: ~/unit-test
      # run integration tests!
      - run: ./gradlew integrationTest
      - run:
          name: Save integration-test results
          command: |
            mkdir -p ~/integration-test/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/integration-test/ \;
          when: always
      - store_test_results:
          path: ~/integration-test
      - run: ./gradlew clean stage -x test
      #store the build jar
      - store_artifacts:
          path: ~/repo/build/libs
