databaseChangeLog:
- changeSet:
    id: 1564425418594-1
    author: albvs (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              primaryKey: true
              primaryKeyName: app_userPK
            name: id
            type: BIGINT
        - column:
            name: user_name
            type: VARCHAR(255)
        tableName: app_user
- changeSet:
    id: 1564425418594-2
    author: albvs (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              primaryKey: true
              primaryKeyName: itemPK
            name: id
            type: BIGINT
        - column:
            name: classification
            type: INTEGER
        - column:
            name: description
            type: VARCHAR(255)
        - column:
            name: name
            type: VARCHAR(255)
        - column:
            name: period
            type: INTEGER
        - column:
            name: item_group_id
            type: BIGINT
        tableName: item
- changeSet:
    id: 1564425418594-3
    author: albvs (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              primaryKey: true
              primaryKeyName: item_groupPK
            name: id
            type: BIGINT
        - column:
            name: description
            type: VARCHAR(255)
        - column:
            name: name
            type: VARCHAR(255)
        - column:
            name: owner_id
            type: BIGINT
        tableName: item_group
- changeSet:
    id: 1564425418594-4
    author: albvs (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
            name: item_id
            type: BIGINT
        - column:
            name: sources
            type: BIGINT
        tableName: item_sources
- changeSet:
    id: 1564425418594-5
    author: albvs (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              primaryKey: true
              primaryKeyName: item_to_sourcePK
            name: id
            type: BIGINT
        - column:
            name: item_id
            type: BIGINT
        - column:
            name: source_id
            type: BIGINT
        tableName: item_to_source
- changeSet:
    id: 1564425418594-6
    author: albvs (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: item_id
        baseTableName: item_sources
        constraintName: FK612laru87joxu29emfututxm8
        deferrable: false
        initiallyDeferred: false
        referencedColumnNames: id
        referencedTableName: item
        validate: true
- changeSet:
    id: 1564425418594-7
    author: albvs (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: owner_id
        baseTableName: item_group
        constraintName: FKfxwpeh0ej7yutw8dc64r0bdih
        deferrable: false
        initiallyDeferred: false
        referencedColumnNames: id
        referencedTableName: app_user
        validate: true
- changeSet:
    id: 1564425418594-8
    author: albvs (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: item_group_id
        baseTableName: item
        constraintName: FKr4fbv7293k0b5v1qjk5lm6md
        deferrable: false
        initiallyDeferred: false
        referencedColumnNames: id
        referencedTableName: item_group
        validate: true

